---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: ".learnwithclyde/dashboard.md"
  label: Dashboard
  read_only: true
- type: heading
  label: Site content
- type: jekyll-pages
  label: Public pages
  create: all
  templates:
  - public-page-template
- type: jekyll-posts
  label: Events
  create: all
  templates:
  - event-template
- type: directory
  path: _teams
  label: Team
  create: all
  match: "**/*"
  templates:
  - team-member-template
- type: heading
  label: Developer content
- type: directory
  path: _includes
  label: Widgets
  create: documents
  match: "**/*.html"
- type: document
  path: _data/SocialNetworks.yml
  label: Social media settings
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
